/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.1.3-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Task;
import org.openapitools.model.TaskWrite;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-11-15T10:10:17.509Z[GMT]")

@Validated
@Api(value = "tasks", description = "the tasks API")
public interface TasksApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "Create a task", nickname = "createTask", notes = "", response = Task.class, tags={ "tasks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Null response", response = Task.class) })
    @RequestMapping(value = "/tasks",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Task> createTask(@ApiParam(value = "" ,required=true )  @Valid @RequestBody TaskWrite taskWrite) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "null");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "delete a task", nickname = "deleteTask", notes = "", tags={ "tasks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "expected response to a valid request") })
    @RequestMapping(value = "/tasks/{taskId}",
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> deleteTask(@ApiParam(value = "id of the task to delete",required=true) @PathVariable("taskId") String taskId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "Info for a specific Task", nickname = "getTaskById", notes = "", response = Task.class, tags={ "tasks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Expected response to a valid request", response = Task.class) })
    @RequestMapping(value = "/tasks/{taskId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Task> getTaskById(@ApiParam(value = "The id of the Task to retrieve",required=true) @PathVariable("taskId") String taskId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "null");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "Get all tasks", nickname = "getTasks", notes = "", response = Task.class, responseContainer = "List", tags={ "tasks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "An array of tasks", response = Task.class, responseContainer = "List") })
    @RequestMapping(value = "/tasks",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Task>> getTasks() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "null");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    @ApiOperation(value = "update a specific task", nickname = "updateTask", notes = "", response = Task.class, tags={ "tasks", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Expected response to a valid request", response = Task.class) })
    @RequestMapping(value = "/tasks/{taskId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    default ResponseEntity<Task> updateTask(@ApiParam(value = "id of the task to update",required=true) @PathVariable("taskId") String taskId,@ApiParam(value = ""  )  @Valid @RequestBody TaskWrite taskWrite) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "null");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
